import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import LogInButton from './LogInButton';
import LogOutButton from './LogOutButton';
import SignUpButton from './SignUpButton';
import DarkModeToggleButton from './DarkModeToggleButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='bg-gray-100 dark:bg-gray-700 dark:text-gray-100'>
          <Link href="/">HOME</Link>
          <Link href="/list">목록</Link>
          {session ? (
            <LogOutButton />
          ) : (
            <>
              <LogInButton />
              <SignUpButton />
            </>
          )}
          <DarkModeToggleButton />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
